# Generated by Django 4.2.16 on 2024-11-10 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('file_management', '0003_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='from_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_files', to='file_management.department'),
        ),
    ]
